// GENERATED — do not edit by hand. Edit shared/, then run:
//   node scripts/sync-humanizer.js

// Canonical AI-likelihood estimator — SINGLE SOURCE OF TRUTH.
// Copies are generated by scripts/sync-humanizer.js:
//   Frontend/src/detector.js  (ES module, Create React App)
//   live-demo/detector.js      (ES module, plain browser)
//   Backend/detector.js        (CommonJS, Node/Express)
// Never edit the copies by hand — edit this file, then run:
//   node scripts/sync-humanizer.js
//
// IMPORTANT: this is a heuristic estimator, not a model like ZeroGPT.
// It measures the same public signals detectors use (marker phrases,
// sentence uniformity, opener repetition, contractions, voice) and turns
// them into a 0-100 estimate. External detectors WILL give different
// numbers. Use it to compare input vs output while humanizing.

// Strong AI-skewed markers (weight ~4.5 per 100 words each, capped).
const STRONG_MARKERS = [
  'furthermore', 'moreover', 'additionally', 'consequently', 'accordingly',
  'nevertheless', 'nonetheless', 'subsequently',
  'in conclusion', 'to summarize', 'in summary',
  'it is important to note', 'it should be noted', 'it is worth noting',
  'due to the fact that', 'for the purpose of', 'in order to',
  'with regard to', 'in terms of', 'with respect to', 'in light of',
  'a multitude of', 'a wide range of', 'a large number of', 'a number of',
  'a variety of', 'a plethora of', 'myriad',
  'in the realm of', 'testament to', 'in the ever-evolving',
  "in today's fast-paced", 'in a fast-paced world',
  'delve', 'tapestry', 'vibrant', 'seamless', 'pivotal', 'crucial',
  'showcase', 'boast', 'embark', 'elevate', 'foster', 'cultivate',
  'utilize', 'utilizes', 'utilization', 'leverage', 'leverages', 'leveraging',
  'comprehensive', 'intricate', 'implement', 'implements', 'implementation',
  'demonstrate', 'demonstrates', 'illustrate', 'illustrates',
  'indicate', 'indicates', 'facilitate', 'facilitates',
  'numerous', 'robust', 'holistic', 'granular', 'actionable', 'impactful',
  'navigate', 'navigates', 'navigating', 'streamline', 'streamlines',
  'optimize', 'optimizes', 'cutting-edge', 'cutting edge',
  'state-of-the-art', 'state of the art', 'groundbreaking', 'innovative',
  'revolutionize', 'revolutionizes', 'underscore', 'underscores',
  'elucidate', 'delineate', 'enumerate', 'firstly', 'secondly',
  'plays a key role', 'play a key role',
  'it goes without saying', 'as a matter of fact', 'prior to',
  'spearhead', 'supercharge', 'take a deep dive',
  'as well as', 'in addition to', 'with the help of',
];

// Mild markers: common in AI text but also in formal human writing.
const MILD_MARKERS = [
  'however', 'therefore', 'thus', 'hence', 'although',
  'in addition', 'overall', 'ultimately', 'significantly', 'notably',
  'importantly', 'essentially', 'fundamentally',
  'first and foremost', 'last but not least', 'each and every',
];

const CONTRACTIONS = [
  "can't", "won't", "don't", "doesn't", "didn't",
  "isn't", "aren't", "wasn't", "weren't",
  "haven't", "hasn't", "hadn't",
  "wouldn't", "shouldn't", "couldn't",
  "it's", "that's", "there's",
  "you'll", "we'll", "they'll", "it'll", "that'll", "i'll",
  "you've", "we've", "they've", "i've",
  "you're", "we're", "they're",
  "you'd", "we'd", "they'd", "i'd",
];

// Casual/human voice words. AI text rarely contains these.
const CASUAL_WORDS = [
  'really', 'pretty', 'kind of', 'sort of', 'a lot',
  'stuff', 'actually', 'honestly', 'frankly', 'basically',
  'anyway', 'yeah', 'yep', 'well,', 'look,', 'right?',
];

const FIRST_PERSON = ['i', 'we', 'you', 'my', 'our', 'your', 'me', 'us'];

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function countOccurrences(text, phrases) {
  let total = 0;
  const found = [];
  for (const p of phrases) {
    const re = new RegExp('\\b' + escapeRegExp(p) + '\\b', 'gi');
    const matches = text.match(re);
    if (matches) {
      total += matches.length;
      if (!found.includes(p.toLowerCase())) found.push(p.toLowerCase());
    }
  }
  return { total, found };
}

function splitSentences(text) {
  const safe = text.replace(/e\.g\./gi, 'EGX').replace(/i\.e\./gi, 'IEX');
  return safe
    .split(/(?<=[.!?])\s+/)
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

function analyzeText(text) {
  const stats = { words: 0, sentences: 0, avgWords: 0, markers: [] };
  if (!text || !text.trim()) {
    return { score: null, reliable: false, reason: 'empty', label: '', signals: [], stats };
  }
  const words = text.trim().split(/\s+/).filter((w) => w.length > 0);
  stats.words = words.length;
  if (stats.words < 15) {
    return { score: null, reliable: false, reason: 'too-short', label: '', signals: [], stats };
  }

  const sentences = splitSentences(text);
  stats.sentences = sentences.length;
  const lens = sentences.map((s) => s.split(/\s+/).filter((w) => w.length > 0).length);
  stats.avgWords = Math.round((lens.reduce((a, b) => a + b, 0) / lens.length) * 10) / 10;

  const signals = [];
  let score = 0;

  // 1) AI marker phrases (up to 40 pts)
  const strong = countOccurrences(text, STRONG_MARKERS);
  const mild = countOccurrences(text, MILD_MARKERS);
  stats.markers = strong.found.slice(0, 6);
  const strongDensity = (strong.total / stats.words) * 100;
  const mildDensity = (mild.total / stats.words) * 100;
  const markerPts = Math.min(40, Math.round(strongDensity * 4.5 + mildDensity * 1.2));
  if (markerPts > 0) {
    score += markerPts;
    const shown = stats.markers.join(', ') || `${mild.total} mild`;
    signals.push({
      label: 'AI marker phrases',
      detail: `${strong.total + mild.total} found (${shown})`,
      points: markerPts,
    });
  }

  // 2) Sentence-length uniformity / burstiness (up to 20 pts)
  if (lens.length >= 3) {
    const mean = lens.reduce((a, b) => a + b, 0) / lens.length;
    const variance = lens.reduce((a, b) => a + (b - mean) * (b - mean), 0) / lens.length;
    const cv = mean > 0 ? Math.sqrt(variance) / mean : 0;
    const uniPts = Math.round(20 * Math.max(0, 1 - cv / 0.55));
    if (uniPts > 0) {
      score += uniPts;
      signals.push({
        label: 'Uniform sentence length',
        detail: `lengths ${Math.min(...lens)}–${Math.max(...lens)} words, low burstiness`,
        points: uniPts,
      });
    }
  }

  // 3) Repeated sentence openers (up to 10 pts)
  if (sentences.length >= 2) {
    const openers = sentences.map((s) => {
      const m = s.toLowerCase().match(/^[a-z]+/);
      return m ? m[0] : '';
    });
    const freq = {};
    openers.forEach((o) => { if (o) freq[o] = (freq[o] || 0) + 1; });
    const repeats = Object.entries(freq).filter(([, n]) => n > 1);
    const dupCount = repeats.reduce((a, [, n]) => a + (n - 1), 0);
    const repPts = Math.min(10, dupCount * 3);
    if (repPts > 0) {
      score += repPts;
      signals.push({
        label: 'Repeated sentence openers',
        detail: repeats.map(([w, n]) => `"${w}" ×${n}`).join(', '),
        points: repPts,
      });
    }
  }

  // 4) No contractions in a longer text (+8)
  const contractions = countOccurrences(text, CONTRACTIONS);
  if (stats.words >= 40 && contractions.total === 0) {
    score += 8;
    signals.push({ label: 'No contractions', detail: `${stats.words} words, none found`, points: 8 });
  }

  // 5) Long average sentence (+8 / +4)
  if (stats.avgWords > 26) {
    score += 8;
    signals.push({ label: 'Long sentences', detail: `avg ${stats.avgWords} words`, points: 8 });
  } else if (stats.avgWords > 20) {
    score += 4;
    signals.push({ label: 'Long sentences', detail: `avg ${stats.avgWords} words`, points: 4 });
  }

  // 6) Impersonal voice: no I/we/you in a longer text (+6)
  const fp = countOccurrences(text, FIRST_PERSON);
  if (stats.words >= 40 && fp.total === 0) {
    score += 6;
    signals.push({ label: 'Impersonal voice', detail: 'no I / we / you', points: 6 });
  }

  // 7) Human relief: casual voice and direct address (down to −20)
  const casual = countOccurrences(text, CASUAL_WORDS);
  const casualDensity = (casual.total / stats.words) * 100;
  let relief = Math.min(16, Math.round(casualDensity * 4));
  if (fp.total > 0) relief = Math.min(20, relief + 4);
  if (relief > 0) {
    score -= relief;
    signals.push({ label: 'Casual, human voice', detail: 'contractions, direct address, natural hedges', points: -relief });
  }

  score = Math.max(0, Math.min(100, Math.round(score)));
  const label = score >= 60 ? 'Likely AI' : score >= 35 ? 'Mixed signals' : 'Likely human';
  return { score, reliable: true, reason: '', label, signals, stats };
}

module.exports = { analyzeText };
