// Canonical Humanize AI engine — SINGLE SOURCE OF TRUTH.
// Copies for each platform are generated by scripts/sync-humanizer.js:
//   Frontend/src/humanizer.js  (ES module, Create React App)
//   live-demo/humanizer.js      (ES module, plain browser)
//   Backend/humanizer.js        (CommonJS, Node/Express)
// Never edit the copies by hand — edit this file, then run:
//   node scripts/sync-humanizer.js

// [pattern, replacement, minLevel?] — pattern is either a plain phrase
// (matched with word boundaries, longest first) or a RegExp (used as-is).
// Replacement is the BASE (lowercase) form; case of each match is preserved
// ("Furthermore" -> "Also"). minLevel gates bold voice changes:
// 0 = all levels, 2 = strong only. Everything is ALWAYS applied within its
// level (no randomness), so output is deterministic.
const REPLACEMENTS = [
  // ---- Famous AI-detector trigger phrases (highest signal first) ----
  ['in today\'s fast-paced world', 'today'],
  ['in the ever-evolving world of', 'in'],
  ['in the ever evolving world of', 'in'],
  ['it is important to note that', 'note that'],
  ['it should be noted that', 'note that'],
  ['it is worth noting that', 'note that'],
  ['due to the fact that', 'because'],
  ['for the purpose of', 'for'],
  ['in order to', 'to'],
  ['with regard to', 'about'],
  ['a large number of', 'many'],
  ['a wide range of', 'many'],
  ['a multitude of', 'many'],
  ['a variety of', 'many'],
  ['a number of', 'several'],
  ['in the realm of', 'in'],
  ['testament to the', 'proof of the'],
  ['testament to', 'proof of'],
  ['in conclusion', 'so'],
  ['to summarize', 'so'],
  ['in summary', 'so'],
  ['in this article', 'here'],
  ['furthermore', 'also'],
  ['additionally', 'also'],
  ['moreover', 'also'],
  ['in addition', 'also'],
  ['nevertheless', 'still'],
  ['nonetheless', 'still'],
  ['consequently', 'so'],
  ['accordingly', 'so'],
  ['therefore', 'so'],
  ['however', 'but'],
  ['although', 'though'],
  ['subsequently', 'later'],
  ['prior to', 'before'],
  ['delve into', 'dig into'],
  ['delves into', 'digs into'],
  ['delved into', 'dug into'],
  ['delving into', 'digging into'],
  ['tapestry of', 'mix of'],
  ['vibrant', 'lively'],
  ['seamlessly', 'smoothly'],
  ['seamless', 'smooth'],
  ['pivotal', 'key'],
  ['crucial', 'key'],
  ['comprehensive', 'wide'],
  ['intricate', 'detailed'],
  ['showcases', 'shows'],
  ['showcase', 'show'],
  ['boasts', 'has'],
  ['boast', 'have'],
  ['embark on', 'start'],
  ['fosters', 'builds'],
  ['foster', 'build'],
  ['elevate', 'raise'],
  ['elevates', 'raises'],

  // ---- Formal -> natural (with inflections, all boundary-safe) ----
  ['utilizing', 'using'],
  ['utilizes', 'uses'],
  ['utilized', 'used'],
  ['utilize', 'use'],
  ['utilization', 'use'],
  ['leveraging', 'using'],
  ['leverages', 'uses'],
  ['leveraged', 'used'],
  ['leverage', 'use'],
  ['harnessing', 'using'],
  ['harnesses', 'uses'],
  ['harnessed', 'used'],
  ['harness', 'use'],
  ['implementing', 'using'],
  ['implements', 'uses'],
  ['implemented', 'used'],
  ['implementation', 'use'],
  ['implement', 'use'],
  ['demonstrating', 'showing'],
  ['demonstrates', 'shows'],
  ['demonstrated', 'showed'],
  ['demonstrate', 'show'],
  ['illustrating', 'showing'],
  ['illustrates', 'shows'],
  ['illustrated', 'showed'],
  ['illustrate', 'show'],
  ['indicating', 'showing'],
  ['indicates', 'shows'],
  ['indicated', 'showed'],
  ['indicate', 'show'],
  ['revealing', 'showing'],
  ['reveals', 'shows'],
  ['revealed', 'showed'],
  ['reveal', 'show'],
  ['facilitates', 'helps'],
  ['facilitated', 'helped'],
  ['facilitate', 'help'],
  ['enables', 'lets'],
  ['enabled', 'let'],
  ['enable', 'let'],
  ['allows', 'lets'],
  ['allowed', 'let'],
  ['ensures', 'makes sure'],
  ['ensured', 'made sure'],
  ['ensure', 'make sure'],
  ['assisting', 'helping'],
  ['assists', 'helps'],
  ['assisted', 'helped'],
  ['assistance', 'help'],
  ['assist', 'help'],
  ['acquiring', 'gaining'],
  ['acquires', 'gains'],
  ['acquired', 'gained'],
  ['acquire', 'gain'],
  ['obtaining', 'getting'],
  ['obtains', 'gets'],
  ['obtained', 'got'],
  ['obtain', 'get'],
  ['receiving', 'getting'],
  ['receives', 'gets'],
  ['received', 'got'],
  ['receive', 'get'],
  ['requiring', 'needing'],
  ['requires', 'needs'],
  ['required', 'needed'],
  ['require', 'need'],
  ['purchasing', 'buying'],
  ['purchases', 'buys'],
  ['purchased', 'bought'],
  ['purchase', 'buy'],
  ['enhancing', 'improving'],
  ['enhances', 'improves'],
  ['enhanced', 'improved'],
  ['enhance', 'improve'],
  ['commencing', 'starting'],
  ['commences', 'starts'],
  ['commenced', 'started'],
  ['commence', 'start'],
  ['conducted', 'carried out'],
  ['conducting', 'carrying out'],
  ['conducts', 'carries out'],
  ['conduct', 'carry out'],
  ['individuals', 'people'],
  ['numerous', 'many'],
  ['multiple', 'many'],
  ['various', 'different'],
  ['several', 'a few'],
  ['sufficient', 'enough'],
  ['significant', 'major'],
  ['substantial', 'large'],

  // ---- Human idioms & phrasing (detectors expect stiff AI wording here) ----
  ['such as', 'like'],
  ['as well as', 'and'],
  ['in addition to', 'besides'],
  ['with the help of', 'using'],
  ['due to', 'because of'],
  ['it goes without saying that', 'obviously,'],
  ['there is no doubt that', 'clearly,'],
  ['it is clear that', 'clearly,'],
  ['as a matter of fact', 'actually'],
  ['at this point in time', 'now'],
  ['in the near future', 'soon'],
  ['first and foremost', 'first'],
  ['last but not least', 'finally'],
  ['each and every', 'every'],
  ['whether or not', 'whether'],
  ['the fact that', 'that'],
  ['in the process of', ''],
  ['in light of', 'given'],
  ['along the lines of', 'like'],
  ['with respect to', 'about'],
  ['in terms of', 'when it comes to'],
  ['firstly', 'first'],
  ['secondly', 'second'],
  ['thirdly', 'third'],
  ['lastly', 'finally'],
  ['in most cases', 'usually'],
  ['in many cases', 'often'],
  ['a great deal of', 'a lot of'],
  ['a significant amount of', 'a lot of'],
  ['a large amount of', 'a lot of'],
  ['a significant number of', 'a lot of'],
  ['somewhat', 'kind of'],
  ['relatively', 'pretty'],
  ['fairly', 'pretty'],
  ['extremely', 'really'],
  ['very important', 'really important'],
  ['very good', 'really good'],
  ['very well', 'really well'],
  ['very useful', 'really useful'],
  ['very common', 'really common'],

  // ---- Ability phrases ----
  ['is able to', 'can'],
  ['are able to', 'can'],
  ['was able to', 'could'],
  ['were able to', 'could'],
  ['has the ability to', 'can'],
  ['have the ability to', 'can'],
  ['had the ability to', 'could'],

  // ---- Stiff verbs -> everyday verbs ----
  ['aims to', 'tries to'],
  ['aim to', 'try to'],
  ['aimed at', 'meant for'],
  ['strives to', 'tries to'],
  ['strive to', 'try to'],
  ['seeks to', 'tries to'],
  ['seek to', 'try to'],
  ['requests', 'asks for'],
  ['requested', 'asked for'],
  ['request', 'ask for'],
  ['inquires', 'asks'],
  ['inquired', 'asked'],
  ['inquire', 'ask'],
  ['informs', 'tells'],
  ['informed', 'told'],
  ['inform', 'tell'],
  ['contact us', 'reach out'],
  ['exploring', 'looking at'],
  ['explores', 'looks at'],
  ['explored', 'looked at'],
  ['explore', 'look at'],
  ['diving into', 'getting into'],
  ['dive into', 'get into'],
  ['streamlining', 'simplifying'],
  ['streamlines', 'simplifies'],
  ['streamlined', 'simplified'],
  ['streamline', 'simplify'],
  ['optimizing', 'improving'],
  ['optimizes', 'improves'],
  ['optimized', 'improved'],
  ['optimize', 'improve'],
  ['maximizing', 'boosting'],
  ['maximizes', 'boosts'],
  ['maximized', 'boosted'],
  ['maximize', 'boost'],
  ['minimizing', 'reducing'],
  ['minimizes', 'reduces'],
  ['minimized', 'reduced'],
  ['minimize', 'reduce'],
  ['accelerating', 'speeding up'],
  ['accelerates', 'speeds up'],
  ['accelerated', 'sped up'],
  ['accelerate', 'speed up'],
  ['spearheading', 'leading'],
  ['spearheads', 'leads'],
  ['spearheaded', 'led'],
  ['spearhead', 'lead'],
  ['underscoring', 'showing'],
  ['underscores', 'shows'],
  ['underscored', 'showed'],
  ['underscore', 'show'],
  ['emphasizing', 'stressing'],
  ['emphasizes', 'stresses'],
  ['emphasized', 'stressed'],
  ['emphasize', 'stress'],
  ['revolutionizing', 'changing'],
  ['revolutionizes', 'changes'],
  ['revolutionized', 'changed'],
  ['revolutionize', 'change'],
  ['cutting-edge', 'latest'],
  ['cutting edge', 'latest'],
  ['state-of-the-art', 'latest'],
  ['state of the art', 'latest'],
  ['supercharge', 'boost'],
  ['supercharges', 'boosts'],
  ['supercharged', 'boosted'],
  ['serves as', 'acts as'],
  ['serve as', 'act as'],
  ['plays a key role in', 'matters a lot for'],
  ['play a key role in', 'matter a lot for'],
  ['the latter', 'the second'],
  ['respectively', 'in that order'],

  // ---- Stiff nouns -> plain nouns ----
  ['aspects', 'parts'],
  ['aspect', 'part'],
  ['elements', 'parts'],
  ['element', 'part'],
  ['components', 'parts'],
  ['component', 'part'],

  // ---- Second person: AI writes impersonally, humans address the reader ----
  ['one can', 'you can'],
  ['one should', 'you should'],
  ['one must', 'you have to'],
  ['it is possible to', 'you can'],
  ['it is easy to', 'you can easily'],

  // ---- Strong-only: bold voice changes (grammatically safe imperatives) ----
  ['it is important to', 'be sure to', 2],
  ['it is essential to', 'be sure to', 2],
  ['it is crucial to', 'make sure to', 2],

  // ---- Raw patterns (capture groups; used as-is) ----
  [/(\d+)\s+percent\b/gi, '$1%'],
  [/(\$?)(\d[\d,]*)\s+dollars\b/gi, (m, dol, num) => (dol || '$') + num],

  // ---- Contractions humans use, AI often avoids (always safe) ----
  ['cannot', "can't"],
  ['do not', "don't"],
  ['does not', "doesn't"],
  ['did not', "didn't"],
  ['will not', "won't"],
  ['would not', "wouldn't"],
  ['should not', "shouldn't"],
  ['could not', "couldn't"],
  ['is not', "isn't"],
  ['are not', "aren't"],
  ['was not', "wasn't"],
  ['were not', "weren't"],
  ['have not', "haven't"],
  ['has not', "hasn't"],
  ['had not', "hadn't"],
  ['it is', "it's"],
  ['that is', "that's"],
  ['there is', "there's"],
  ['you will', "you'll"],
  ['we will', "we'll"],
  ['they will', "they'll"],
  ['it will', "it'll"],
  ['that will', "that'll"],
  ['i will', "I'll"],
  ['you have', "you've"],
  ['we have', "we've"],
  ['they have', "they've"],
  ['i have', "I've"],
  ['you are', "you're"],
  ['we are', "we're"],
  ['they are', "they're"],
  ['you would', "you'd"],
  ['we would', "we'd"],
  ['they would', "they'd"],
  ['i would', "I'd"],
];

// Sentence openers that scream "AI" when repeated. Normalized to a natural
// base form first; consecutive duplicates are then rotated to a synonym so
// no two sentences in a row start the same way (a strong detector signal).
const OPENER_BASE = [
  ['moreover,', 'also,'],
  ['furthermore,', 'also,'],
  ['additionally,', 'also,'],
  ['in addition,', 'also,'],
  ['however,', 'but,'],
  ['therefore,', 'so,'],
  ['thus,', 'so,'],
  ['hence,', 'so,'],
  ['nevertheless,', 'still,'],
  ['nonetheless,', 'still,'],
  ['in conclusion,', 'so,'],
  ['lastly,', 'finally,'],
];
const OPENER_ROTATION = {
  'also,': ['also,', 'plus,', 'and,'],
  'but,': ['but,', 'still,'],
  'so,': ['so,', 'then,'],
  'still,': ['still,', 'but,'],
  'and,': ['and,', 'plus,', 'also,'],
};

const STRONG_FILLERS = ['honestly', 'frankly', 'basically', 'look'];

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Abbreviations that contain periods must survive the whole pipeline
// (splitting + capitalization), so they are masked at the start and
// restored at the very end.
const EG_TOKEN = 'E\x1bG';
const IE_TOKEN = 'I\x1bE';

export class TextHumanizer {
  preserveCase(match, replacement) {
    if (!match || !replacement) return replacement;
    if (match === match.toUpperCase()) return replacement.toUpperCase();
    if (match[0] === match[0].toUpperCase()) {
      return replacement[0].toUpperCase() + replacement.slice(1);
    }
    return replacement;
  }

  applyReplacements(text, level = 0) {
    // Longest patterns first so "a large number of" wins over shorter ones.
    const keyLen = (e) => (e[0] instanceof RegExp ? e[0].source.length : e[0].length);
    const entries = [...REPLACEMENTS].sort((a, b) => keyLen(b) - keyLen(a));
    for (const [src, rep, minLevel = 0] of entries) {
      if (level < minLevel) continue;
      if (src instanceof RegExp) {
        // Raw pattern: fresh instance each call (avoids lastIndex state bugs).
        text = text.replace(new RegExp(src.source, src.flags), rep);
      } else {
        const re = new RegExp('\\b' + escapeRegExp(src) + '\\b', 'gi');
        text = text.replace(re, (m) => this.preserveCase(m, rep));
      }
    }
    return text;
  }

  splitSentences(text) {
    // Tokens contain no periods, so abbreviations never cause a split.
    const parts = text
      .split(/(?<=[.!?])\s+(?=[A-Z0-9"'“(\[])/)
      .map((s) => s.trim())
      .filter((s) => s.length > 0);
    return parts.length > 0 ? parts : [text.trim()];
  }

  // Break sentences longer than maxWords at a natural joint. Splitting long,
  // uniform AI sentences into mixed short/long ones creates "burstiness" —
  // the main thing detectors measure. Splits at because/while/when produce
  // fragment-style sentences ("Because it's faster."), which humans write
  // constantly and AI almost never does.
  splitLongSentences(sentences, maxWords, mode) {
    // A which/that split is only grammatical if a verb follows
    // ("Which means X." works; "Which often Big..." does not).
    const verbGuard = /^(is|was|are|were|will|would|can|could|has|have|had|means|meant|makes|made)\b/i;
    const lightJoints = [
      { re: /; / }, { re: /, and /i }, { re: /, but /i }, { re: /, or /i },
      { re: /, so /i }, { re: / which /i, guard: true }, { re: / that /i, guard: true },
      { re: / because /i }, { re: / while /i }, { re: / whereas /i },
    ];
    const boldJoints = [
      // Lookahead joints KEEP the conjunction so the new sentence reads
      // "Because it's faster." / "While most tools..." — human fragments.
      { re: / (?=because\b)/i }, { re: / (?=while\b)/i }, { re: / (?=whereas\b)/i },
      { re: / (?=when\b)/i }, { re: / (?=if\b)/i }, { re: / (?=though\b)/i },
      { re: / (?=although\b)/i },
      { re: / (?=which\b)/i, guard: true }, { re: / (?=that\b)/i, guard: true },
      { re: /; / },
      { re: /, and /i }, { re: /, but /i }, { re: /, or /i }, { re: /, so /i },
    ];
    // Strong: bare-comma splits that KEEP the conjunction ("apples. And
    // oranges.") — fragment rhythm, still grammatical thanks to FANBOYS.
    const strongJoints = [
      { re: / (?=because\b)/i }, { re: / (?=while\b)/i }, { re: / (?=whereas\b)/i },
      { re: / (?=when\b)/i }, { re: / (?=if\b)/i }, { re: / (?=though\b)/i },
      { re: / (?=although\b)/i },
      { re: / (?=which\b)/i, guard: true }, { re: / (?=that\b)/i, guard: true },
      { re: /; / },
      { re: /, (?=and\b)/i }, { re: /, (?=or\b)/i }, { re: /, (?=but\b)/i },
      { re: /, (?=so\b)/i }, { re: /, (?=yet\b)/i },
      { re: /, and /i }, { re: /, but /i }, { re: /, or /i }, { re: /, so /i },
    ];
    const joints = mode === 'strong' ? strongJoints : mode === 'medium' ? boldJoints : lightJoints;
    const out = [];
    for (const s of sentences) {
      const words = s.split(/\s+/);
      if (words.length <= maxWords) {
        out.push(s);
        continue;
      }
      let splitAt = -1;
      let jointLen = 0;
      for (const j of joints) {
        const rx = new RegExp(j.re.source, 'gi');
        let m;
        while ((m = rx.exec(s)) !== null) {
          // Split off-center is fine (fragments are human); avoid stubs.
          if (m.index < s.length * 0.15 || m.index > s.length * 0.85) continue;
          const after = s.slice(m.index + m[0].length).trim();
          // For which/that splits, the word AFTER the conjunction needs a verb.
          if (j.guard && !verbGuard.test(after.replace(/^(which|that)\b\s*/i, ''))) continue;
          splitAt = m.index;
          jointLen = m[0].length;
          break;
        }
        if (splitAt !== -1) break;
      }
      if (splitAt === -1) {
        out.push(s);
        continue;
      }
      const first = s.slice(0, splitAt).replace(/[,;]$/, '').trim() + '.';
      let second = s.slice(splitAt + jointLen).trim();
      second = second.charAt(0).toUpperCase() + second.slice(1);
      out.push(first, second);
    }
    return out;
  }

  normalizeOpeners(sentences) {
    // 1) map AI openers to their natural base form (case-preserving)
    let mapped = sentences.map((s) => {
      for (const [src, rep] of OPENER_BASE) {
        const re = new RegExp('^' + escapeRegExp(src) + '\\s+', 'i');
        const m = s.match(re);
        if (m) return this.preserveCase(m[0].trim(), rep) + ' ' + s.slice(m[0].length);
      }
      return s;
    });
    // 2) rotate consecutive duplicates: "Also, ... Also, ..." never survives
    const seen = {};
    mapped = mapped.map((s) => {
      const m = s.match(/^([A-Za-z]+,)\s+/);
      if (!m) return s;
      const key = m[1].toLowerCase();
      const variants = OPENER_ROTATION[key];
      if (!variants) return s;
      seen[key] = (seen[key] || 0) + 1;
      const pick = variants[(seen[key] - 1) % variants.length];
      if (pick.toLowerCase() === key) return s;
      const cap = m[1][0] === m[1][0].toUpperCase();
      const word = cap ? pick[0].toUpperCase() + pick.slice(1) : pick;
      return word + ' ' + s.slice(m[0].length);
    });
    return mapped;
  }

  normalizePunctuation(text) {
    let t = text;
    t = t.replace(/ — /g, ', ');
    t = t.replace(/ – /g, ', ');
    // Semicolons joining clauses -> full stop (humans use short sentences).
    t = t.replace(/;\s*/g, '. ');
    t = t.replace(/\s+([.,!?;:])/g, '$1'); // no space before punctuation
    t = t.replace(/([.,!?;:])([A-Za-z])/g, '$1 $2'); // space after punctuation
    t = t.replace(/\s+/g, ' ').trim();
    // Capitalize the first letter of every sentence.
    t = t.replace(/(^|[.!?]\s+)([a-z])/g, (m, p1, p2) => p1 + p2.toUpperCase());
    // Standalone "i" -> "I".
    t = t.replace(/\bi\b/g, 'I');
    return t;
  }

  humanize(text, intensity = 'medium') {
    if (!text || !text.trim()) return text;
    const level = intensity === 'light' ? 0 : intensity === 'strong' ? 2 : 1;

    let result = text
      .replace(/e\.g\./gi, EG_TOKEN)
      .replace(/i\.e\./gi, IE_TOKEN);
    result = this.applyReplacements(result, level);
    let sentences = this.splitSentences(result);

    const maxWords = intensity === 'light' ? 1000 : intensity === 'strong' ? 18 : 24;
    if (maxWords < 1000) {
      sentences = this.splitLongSentences(sentences, maxWords, intensity);
    }

    sentences = this.normalizeOpeners(sentences);

    if (intensity === 'strong' && sentences.length > 1) {
      // One deterministic casual touch (never random): first plain sentence
      // after the opening one gets a conversational prefix.
      const filler = STRONG_FILLERS[sentences.length % STRONG_FILLERS.length];
      for (let i = 1; i < sentences.length; i++) {
        // Skip openers ("Plus, ...") and conjunction-led fragments
        // ("Because ..." + "Basically," would read redundantly).
        if (!/^[A-Za-z]+,/.test(sentences[i]) &&
            !/^(because|while|whereas|when|if|though|although|which|that|and|but|so|or|plus|also)\b/i.test(sentences[i])) {
          sentences[i] = filler[0].toUpperCase() + filler.slice(1) + ', ' +
            sentences[i].charAt(0).toLowerCase() + sentences[i].slice(1);
          break;
        }
      }
      // Rhetorical closer: "..., right?" — very human, very unpredictable
      // for detectors. Only on a plain short closing statement.
      if (sentences.length >= 3) {
        const last = sentences[sentences.length - 1];
        if (/\.$/.test(last) && last.split(/\s+/).length <= 20) {
          sentences[sentences.length - 1] = last.replace(/\.$/, ', right?');
        }
      }
    }

    result = this.normalizePunctuation(sentences.join(' '));
    result = result.split(EG_TOKEN).join('e.g.').split(IE_TOKEN).join('i.e.');
    return result;
  }
}

export const humanizer = new TextHumanizer();

export default humanizer;
