// Canonical Humanize AI engine — SINGLE SOURCE OF TRUTH.
// Copies for each platform are generated by scripts/sync-humanizer.js:
//   Frontend/src/humanizer.js  (ES module, Create React App)
//   live-demo/humanizer.js      (ES module, plain browser)
//   Backend/humanizer.js        (CommonJS, Node/Express)
// Never edit the copies by hand — edit this file, then run:
//   node scripts/sync-humanizer.js

// [phrase, replacement] — replacement is the BASE (lowercase) form.
// Case of each match is preserved at runtime ("Furthermore" -> "Also").
// Every entry is matched with word boundaries, longest phrases first,
// and ALWAYS applied (no randomness), so output is deterministic.
const REPLACEMENTS = [
  // ---- Famous AI-detector trigger phrases (highest signal first) ----
  ['in today\'s fast-paced world', 'today'],
  ['in the ever-evolving world of', 'in'],
  ['in the ever evolving world of', 'in'],
  ['it is important to note that', 'note that'],
  ['it should be noted that', 'note that'],
  ['it is worth noting that', 'note that'],
  ['due to the fact that', 'because'],
  ['for the purpose of', 'for'],
  ['in order to', 'to'],
  ['with regard to', 'about'],
  ['a large number of', 'many'],
  ['a wide range of', 'many'],
  ['a multitude of', 'many'],
  ['a variety of', 'many'],
  ['a number of', 'several'],
  ['in the realm of', 'in'],
  ['testament to the', 'proof of the'],
  ['testament to', 'proof of'],
  ['in conclusion', 'so'],
  ['to summarize', 'so'],
  ['in summary', 'so'],
  ['in this article', 'here'],
  ['furthermore', 'also'],
  ['additionally', 'also'],
  ['moreover', 'also'],
  ['in addition', 'also'],
  ['nevertheless', 'still'],
  ['nonetheless', 'still'],
  ['consequently', 'so'],
  ['accordingly', 'so'],
  ['therefore', 'so'],
  ['however', 'but'],
  ['although', 'though'],
  ['subsequently', 'later'],
  ['prior to', 'before'],
  ['delve into', 'dig into'],
  ['delves into', 'digs into'],
  ['delved into', 'dug into'],
  ['delving into', 'digging into'],
  ['tapestry of', 'mix of'],
  ['vibrant', 'lively'],
  ['seamlessly', 'smoothly'],
  ['seamless', 'smooth'],
  ['pivotal', 'key'],
  ['crucial', 'key'],
  ['comprehensive', 'wide'],
  ['intricate', 'detailed'],
  ['showcases', 'shows'],
  ['showcase', 'show'],
  ['boasts', 'has'],
  ['boast', 'have'],
  ['embark on', 'start'],
  ['fosters', 'builds'],
  ['foster', 'build'],
  ['elevate', 'raise'],
  ['elevates', 'raises'],

  // ---- Formal -> natural (with inflections, all boundary-safe) ----
  ['utilizing', 'using'],
  ['utilizes', 'uses'],
  ['utilized', 'used'],
  ['utilize', 'use'],
  ['utilization', 'use'],
  ['leveraging', 'using'],
  ['leverages', 'uses'],
  ['leveraged', 'used'],
  ['leverage', 'use'],
  ['harnessing', 'using'],
  ['harnesses', 'uses'],
  ['harnessed', 'used'],
  ['harness', 'use'],
  ['implementing', 'using'],
  ['implements', 'uses'],
  ['implemented', 'used'],
  ['implementation', 'use'],
  ['implement', 'use'],
  ['demonstrating', 'showing'],
  ['demonstrates', 'shows'],
  ['demonstrated', 'showed'],
  ['demonstrate', 'show'],
  ['illustrating', 'showing'],
  ['illustrates', 'shows'],
  ['illustrated', 'showed'],
  ['illustrate', 'show'],
  ['indicating', 'showing'],
  ['indicates', 'shows'],
  ['indicated', 'showed'],
  ['indicate', 'show'],
  ['revealing', 'showing'],
  ['reveals', 'shows'],
  ['revealed', 'showed'],
  ['reveal', 'show'],
  ['facilitates', 'helps'],
  ['facilitated', 'helped'],
  ['facilitate', 'help'],
  ['enables', 'lets'],
  ['enabled', 'let'],
  ['enable', 'let'],
  ['allows', 'lets'],
  ['allowed', 'let'],
  ['ensures', 'makes sure'],
  ['ensured', 'made sure'],
  ['ensure', 'make sure'],
  ['assisting', 'helping'],
  ['assists', 'helps'],
  ['assisted', 'helped'],
  ['assistance', 'help'],
  ['assist', 'help'],
  ['acquiring', 'gaining'],
  ['acquires', 'gains'],
  ['acquired', 'gained'],
  ['acquire', 'gain'],
  ['obtaining', 'getting'],
  ['obtains', 'gets'],
  ['obtained', 'got'],
  ['obtain', 'get'],
  ['receiving', 'getting'],
  ['receives', 'gets'],
  ['received', 'got'],
  ['receive', 'get'],
  ['requiring', 'needing'],
  ['requires', 'needs'],
  ['required', 'needed'],
  ['require', 'need'],
  ['purchasing', 'buying'],
  ['purchases', 'buys'],
  ['purchased', 'bought'],
  ['purchase', 'buy'],
  ['enhancing', 'improving'],
  ['enhances', 'improves'],
  ['enhanced', 'improved'],
  ['enhance', 'improve'],
  ['commencing', 'starting'],
  ['commences', 'starts'],
  ['commenced', 'started'],
  ['commence', 'start'],
  ['conducted', 'carried out'],
  ['conducting', 'carrying out'],
  ['conducts', 'carries out'],
  ['conduct', 'carry out'],
  ['individuals', 'people'],
  ['numerous', 'many'],
  ['multiple', 'many'],
  ['various', 'different'],
  ['several', 'a few'],
  ['sufficient', 'enough'],
  ['significant', 'major'],
  ['substantial', 'large'],

  // ---- Contractions humans use, AI often avoids (always safe) ----
  ['cannot', "can't"],
  ['do not', "don't"],
  ['does not', "doesn't"],
  ['did not', "didn't"],
  ['will not', "won't"],
  ['would not', "wouldn't"],
  ['should not', "shouldn't"],
  ['could not', "couldn't"],
  ['is not', "isn't"],
  ['are not', "aren't"],
  ['was not', "wasn't"],
  ['were not', "weren't"],
  ['have not', "haven't"],
  ['has not', "hasn't"],
  ['had not', "hadn't"],
  ['it is', "it's"],
  ['that is', "that's"],
  ['there is', "there's"],
];

// Sentence openers that scream "AI" when repeated. Normalized to a natural
// base form first; consecutive duplicates are then rotated to a synonym so
// no two sentences in a row start the same way (a strong detector signal).
const OPENER_BASE = [
  ['moreover,', 'also,'],
  ['furthermore,', 'also,'],
  ['additionally,', 'also,'],
  ['in addition,', 'also,'],
  ['however,', 'but,'],
  ['therefore,', 'so,'],
  ['thus,', 'so,'],
  ['hence,', 'so,'],
  ['nevertheless,', 'still,'],
  ['nonetheless,', 'still,'],
  ['in conclusion,', 'so,'],
];
const OPENER_ROTATION = {
  'also,': ['also,', 'plus,', 'and,'],
  'but,': ['but,', 'still,'],
  'so,': ['so,', 'then,'],
  'still,': ['still,', 'but,'],
};

const STRONG_FILLERS = ['honestly', 'basically', 'frankly'];

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Abbreviations that contain periods must survive the whole pipeline
// (splitting + capitalization), so they are masked at the start and
// restored at the very end.
const EG_TOKEN = 'E\x1bG';
const IE_TOKEN = 'I\x1bE';

export class TextHumanizer {
  preserveCase(match, replacement) {
    if (!match || !replacement) return replacement;
    if (match === match.toUpperCase()) return replacement.toUpperCase();
    if (match[0] === match[0].toUpperCase()) {
      return replacement[0].toUpperCase() + replacement.slice(1);
    }
    return replacement;
  }

  applyReplacements(text) {
    // Longest phrases first so "a large number of" wins over "a number of".
    const entries = [...REPLACEMENTS].sort((a, b) => b[0].length - a[0].length);
    for (const [src, rep] of entries) {
      const re = new RegExp('\\b' + escapeRegExp(src) + '\\b', 'gi');
      text = text.replace(re, (m) => this.preserveCase(m, rep));
    }
    return text;
  }

  splitSentences(text) {
    // Tokens contain no periods, so abbreviations never cause a split.
    const parts = text
      .split(/(?<=[.!?])\s+(?=[A-Z0-9"'“(\[])/)
      .map((s) => s.trim())
      .filter((s) => s.length > 0);
    return parts.length > 0 ? parts : [text.trim()];
  }

  // Break sentences longer than maxWords at a natural joint. Splitting long,
  // uniform AI sentences into mixed short/long ones creates "burstiness" —
  // the main thing detectors measure.
  splitLongSentences(sentences, maxWords) {
    const joints = [
      /, and /i, /, but /i, /, or /i, /, so /i, /; /,
      / which /i, / that /i, / because /i, / while /i, / whereas /i,
    ];
    const out = [];
    for (const s of sentences) {
      const words = s.split(/\s+/);
      if (words.length <= maxWords) {
        out.push(s);
        continue;
      }
      let splitAt = -1;
      let jointLen = 0;
      for (const j of joints) {
        const m = j.exec(s);
        // Split near the middle so both halves read naturally.
        if (m && m.index > s.length * 0.3 && m.index < s.length * 0.75) {
          splitAt = m.index;
          jointLen = m[0].length;
          break;
        }
      }
      if (splitAt === -1) {
        out.push(s);
        continue;
      }
      const first = s.slice(0, splitAt).replace(/[,;]$/, '').trim() + '.';
      let second = s.slice(splitAt + jointLen).trim();
      second = second.charAt(0).toUpperCase() + second.slice(1);
      out.push(first, second);
    }
    return out;
  }

  normalizeOpeners(sentences) {
    // 1) map AI openers to their natural base form (case-preserving)
    let mapped = sentences.map((s) => {
      for (const [src, rep] of OPENER_BASE) {
        const re = new RegExp('^' + escapeRegExp(src) + '\\s+', 'i');
        const m = s.match(re);
        if (m) return this.preserveCase(m[0].trim(), rep) + ' ' + s.slice(m[0].length);
      }
      return s;
    });
    // 2) rotate consecutive duplicates: "Also, ... Also, ..." never survives
    const seen = {};
    mapped = mapped.map((s) => {
      const m = s.match(/^([A-Za-z]+,)\s+/);
      if (!m) return s;
      const key = m[1].toLowerCase();
      const variants = OPENER_ROTATION[key];
      if (!variants) return s;
      seen[key] = (seen[key] || 0) + 1;
      const pick = variants[(seen[key] - 1) % variants.length];
      if (pick.toLowerCase() === key) return s;
      const cap = m[1][0] === m[1][0].toUpperCase();
      const word = cap ? pick[0].toUpperCase() + pick.slice(1) : pick;
      return word + ' ' + s.slice(m[0].length);
    });
    return mapped;
  }

  normalizePunctuation(text) {
    let t = text;
    t = t.replace(/ — /g, ', ');
    t = t.replace(/ – /g, ', ');
    // Semicolons joining clauses -> full stop (humans use short sentences).
    t = t.replace(/;\s*/g, '. ');
    t = t.replace(/\s+([.,!?;:])/g, '$1'); // no space before punctuation
    t = t.replace(/([.,!?;:])([A-Za-z])/g, '$1 $2'); // space after punctuation
    t = t.replace(/\s+/g, ' ').trim();
    // Capitalize the first letter of every sentence.
    t = t.replace(/(^|[.!?]\s+)([a-z])/g, (m, p1, p2) => p1 + p2.toUpperCase());
    // Standalone "i" -> "I".
    t = t.replace(/\bi\b/g, 'I');
    return t;
  }

  humanize(text, intensity = 'medium') {
    if (!text || !text.trim()) return text;

    let result = text
      .replace(/e\.g\./gi, EG_TOKEN)
      .replace(/i\.e\./gi, IE_TOKEN);
    result = this.applyReplacements(result);
    let sentences = this.splitSentences(result);

    const maxWords = intensity === 'light' ? 1000 : intensity === 'strong' ? 18 : 24;
    if (maxWords < 1000) {
      sentences = this.splitLongSentences(sentences, maxWords);
    }

    sentences = this.normalizeOpeners(sentences);

    if (intensity === 'strong' && sentences.length > 1) {
      // One deterministic casual touch on the 2nd sentence (never random).
      const filler = STRONG_FILLERS[sentences.length % STRONG_FILLERS.length];
      if (!/^[A-Za-z]+,/.test(sentences[1])) {
        sentences[1] = filler[0].toUpperCase() + filler.slice(1) + ', ' +
          sentences[1].charAt(0).toLowerCase() + sentences[1].slice(1);
      }
    }

    result = this.normalizePunctuation(sentences.join(' '));
    result = result.split(EG_TOKEN).join('e.g.').split(IE_TOKEN).join('i.e.');
    return result;
  }
}

export const humanizer = new TextHumanizer();

export default humanizer;
