// Canonical Humanize AI engine — SINGLE SOURCE OF TRUTH.
// Copies for each platform are generated by scripts/sync-humanizer.js:
//   Frontend/src/humanizer.js  (ES module, Create React App)
//   live-demo/humanizer.js      (ES module, plain browser)
//   Backend/humanizer.js        (CommonJS, Node/Express)
// Never edit the copies by hand — edit this file, then run:
//   node scripts/sync-humanizer.js

// [pattern, replacement, minLevel?] — pattern is either a plain phrase
// (matched with word boundaries, longest first) or a RegExp (used as-is).
// Replacement is the BASE (lowercase) form; case of each match is preserved
// ("Furthermore" -> "Also"). minLevel gates bold voice changes:
// 0 = all levels, 2 = strong only. Everything is ALWAYS applied within its
// level (no randomness), so output is deterministic.
const REPLACEMENTS = [
  // ---- Famous AI-detector trigger phrases (highest signal first) ----
  ['in today\'s fast-paced world', 'today'],
  ['in the ever-evolving world of', 'in'],
  ['in the ever evolving world of', 'in'],
  ['it is important to note that', 'note that'],
  ['it should be noted that', 'note that'],
  ['it is worth noting that', 'note that'],
  ['due to the fact that', 'because'],
  ['for the purpose of', 'for'],
  ['in order to', 'to'],
  ['with regard to', 'about'],
  ['a large number of', 'many'],
  ['a wide range of', 'many'],
  ['a multitude of', 'many'],
  ['a variety of', 'many'],
  ['a number of', 'several'],
  ['in the realm of', 'in'],
  ['testament to the', 'proof of the'],
  ['testament to', 'proof of'],
  ['in conclusion', 'so'],
  ['to summarize', 'so'],
  ['in summary', 'so'],
  ['in this article', 'here'],
  ['furthermore', 'also'],
  ['additionally', 'also'],
  ['moreover', 'also'],
  ['in addition', 'also'],
  ['nevertheless', 'still'],
  ['nonetheless', 'still'],
  ['consequently', 'so'],
  ['accordingly', 'so'],
  ['therefore', 'so'],
  ['however', 'but'],
  ['although', 'though'],
  ['subsequently', 'later'],
  ['prior to', 'before'],
  ['delve into', 'dig into'],
  ['delves into', 'digs into'],
  ['delved into', 'dug into'],
  ['delving into', 'digging into'],
  ['tapestry of', 'mix of'],
  ['vibrant', 'lively'],
  ['seamlessly', 'smoothly'],
  ['seamless', 'smooth'],
  ['pivotal', 'key'],
  ['crucial', 'key'],
  ['comprehensive', 'wide'],
  ['intricate', 'detailed'],
  ['showcases', 'shows'],
  ['showcase', 'show'],
  ['boasts', 'has'],
  ['boast', 'have'],
  ['embark on', 'start'],
  ['fosters', 'builds'],
  ['foster', 'build'],
  ['elevate', 'raise'],
  ['elevates', 'raises'],

  // ---- Formal -> natural (with inflections, all boundary-safe) ----
  ['utilizing', 'using'],
  ['utilizes', 'uses'],
  ['utilized', 'used'],
  ['utilize', 'use'],
  ['utilization', 'use'],
  ['leveraging', 'using'],
  ['leverages', 'uses'],
  ['leveraged', 'used'],
  ['leverage', 'use'],
  ['harnessing', 'using'],
  ['harnesses', 'uses'],
  ['harnessed', 'used'],
  ['harness', 'use'],
  ['implementing', 'using'],
  ['implements', 'uses'],
  ['implemented', 'used'],
  ['implementation', 'use'],
  ['implement', 'use'],
  ['demonstrating', 'showing'],
  ['demonstrates', 'shows'],
  ['demonstrated', 'showed'],
  ['demonstrate', 'show'],
  ['illustrating', 'showing'],
  ['illustrates', 'shows'],
  ['illustrated', 'showed'],
  ['illustrate', 'show'],
  ['indicating', 'showing'],
  ['indicates', 'shows'],
  ['indicated', 'showed'],
  ['indicate', 'show'],
  ['revealing', 'showing'],
  ['reveals', 'shows'],
  ['revealed', 'showed'],
  ['reveal', 'show'],
  ['facilitates', 'helps'],
  ['facilitated', 'helped'],
  ['facilitate', 'help'],
  ['enables', 'lets'],
  ['enabled', 'let'],
  ['enable', 'let'],
  ['allows', 'lets'],
  ['allowed', 'let'],
  ['ensures', 'makes sure'],
  ['ensured', 'made sure'],
  ['ensure', 'make sure'],
  ['assisting', 'helping'],
  ['assists', 'helps'],
  ['assisted', 'helped'],
  ['assistance', 'help'],
  ['assist', 'help'],
  ['acquiring', 'gaining'],
  ['acquires', 'gains'],
  ['acquired', 'gained'],
  ['acquire', 'gain'],
  ['obtaining', 'getting'],
  ['obtains', 'gets'],
  ['obtained', 'got'],
  ['obtain', 'get'],
  ['receiving', 'getting'],
  ['receives', 'gets'],
  ['received', 'got'],
  ['receive', 'get'],
  ['requiring', 'needing'],
  ['requires', 'needs'],
  ['required', 'needed'],
  ['require', 'need'],
  ['purchasing', 'buying'],
  ['purchases', 'buys'],
  ['purchased', 'bought'],
  ['purchase', 'buy'],
  ['enhancing', 'improving'],
  ['enhances', 'improves'],
  ['enhanced', 'improved'],
  ['enhance', 'improve'],
  ['commencing', 'starting'],
  ['commences', 'starts'],
  ['commenced', 'started'],
  ['commence', 'start'],
  ['conducted', 'carried out'],
  ['conducting', 'carrying out'],
  ['conducts', 'carries out'],
  ['conduct', 'carry out'],
  ['individuals', 'people'],
  ['numerous', 'many'],
  ['multiple', 'many'],
  ['various', 'different'],
  ['several', 'a few'],
  ['sufficient', 'enough'],
  ['significant', 'major'],
  ['substantial', 'large'],

  // ---- Human idioms & phrasing (detectors expect stiff AI wording here) ----
  ['such as', 'like'],
  ['as well as', 'and'],
  ['in addition to', 'besides'],
  ['with the help of', 'using'],
  ['due to', 'because of'],
  ['it goes without saying that', 'obviously,'],
  ['there is no doubt that', 'clearly,'],
  ['it is clear that', 'clearly,'],
  ['as a matter of fact', 'actually'],
  ['at this point in time', 'now'],
  ['in the near future', 'soon'],
  ['first and foremost', 'first'],
  ['last but not least', 'finally'],
  ['each and every', 'every'],
  ['whether or not', 'whether'],
  ['the fact that', 'that'],
  ['in the process of', ''],
  ['in light of', 'given'],
  ['along the lines of', 'like'],
  ['with respect to', 'about'],
  ['in terms of', 'when it comes to'],
  ['firstly', 'first'],
  ['secondly', 'second'],
  ['thirdly', 'third'],
  ['lastly', 'finally'],
  ['in most cases', 'usually'],
  ['in many cases', 'often'],
  ['a great deal of', 'a lot of'],
  ['a significant amount of', 'a lot of'],
  ['a large amount of', 'a lot of'],
  ['a significant number of', 'a lot of'],
  ['somewhat', 'kind of'],
  ['relatively', 'pretty'],
  ['fairly', 'pretty'],
  ['extremely', 'really'],
  ['very important', 'really important'],
  ['very good', 'really good'],
  ['very well', 'really well'],
  ['very useful', 'really useful'],
  ['very common', 'really common'],

  // ---- Ability phrases ----
  ['is able to', 'can'],
  ['are able to', 'can'],
  ['was able to', 'could'],
  ['were able to', 'could'],
  ['has the ability to', 'can'],
  ['have the ability to', 'can'],
  ['had the ability to', 'could'],

  // ---- Stiff verbs -> everyday verbs ----
  ['aims to', 'tries to'],
  ['aim to', 'try to'],
  ['aimed at', 'meant for'],
  ['strives to', 'tries to'],
  ['strive to', 'try to'],
  ['seeks to', 'tries to'],
  ['seek to', 'try to'],
  ['requests', 'asks for'],
  ['requested', 'asked for'],
  ['request', 'ask for'],
  ['inquires', 'asks'],
  ['inquired', 'asked'],
  ['inquire', 'ask'],
  ['informs', 'tells'],
  ['informed', 'told'],
  ['inform', 'tell'],
  ['contact us', 'reach out'],
  ['exploring', 'looking at'],
  ['explores', 'looks at'],
  ['explored', 'looked at'],
  ['explore', 'look at'],
  ['diving into', 'getting into'],
  ['dive into', 'get into'],
  ['streamlining', 'simplifying'],
  ['streamlines', 'simplifies'],
  ['streamlined', 'simplified'],
  ['streamline', 'simplify'],
  ['optimizing', 'improving'],
  ['optimizes', 'improves'],
  ['optimized', 'improved'],
  ['optimize', 'improve'],
  ['maximizing', 'boosting'],
  ['maximizes', 'boosts'],
  ['maximized', 'boosted'],
  ['maximize', 'boost'],
  ['minimizing', 'reducing'],
  ['minimizes', 'reduces'],
  ['minimized', 'reduced'],
  ['minimize', 'reduce'],
  ['accelerating', 'speeding up'],
  ['accelerates', 'speeds up'],
  ['accelerated', 'sped up'],
  ['accelerate', 'speed up'],
  ['spearheading', 'leading'],
  ['spearheads', 'leads'],
  ['spearheaded', 'led'],
  ['spearhead', 'lead'],
  ['underscoring', 'showing'],
  ['underscores', 'shows'],
  ['underscored', 'showed'],
  ['underscore', 'show'],
  ['emphasizing', 'stressing'],
  ['emphasizes', 'stresses'],
  ['emphasized', 'stressed'],
  ['emphasize', 'stress'],
  ['revolutionizing', 'changing'],
  ['revolutionizes', 'changes'],
  ['revolutionized', 'changed'],
  ['revolutionize', 'change'],
  ['cutting-edge', 'latest'],
  ['cutting edge', 'latest'],
  ['state-of-the-art', 'latest'],
  ['state of the art', 'latest'],
  ['supercharge', 'boost'],
  ['supercharges', 'boosts'],
  ['supercharged', 'boosted'],
  ['serves as', 'acts as'],
  ['serve as', 'act as'],
  ['plays a key role in', 'matters a lot for'],
  ['play a key role in', 'matter a lot for'],
  ['the latter', 'the second'],
  ['respectively', 'in that order'],

  // ---- More AI-favorite words -> plain words ----
  ['vital', 'key'],
  ['paramount', 'key'],
  ['robust', 'strong'],
  ['holistic', 'full'],
  ['granular', 'detailed'],
  ['actionable', 'useful'],
  ['impactful', 'big'],
  ['navigating', 'handling'],
  ['navigates', 'handles'],
  ['navigated', 'handled'],
  ['navigate', 'handle'],
  ['cultivating', 'building'],
  ['cultivates', 'builds'],
  ['cultivated', 'built'],
  ['cultivate', 'build'],
  ['poised to', 'ready to'],
  ['myriad', 'many'],
  ['a plethora of', 'a lot of'],
  ['take a deep dive into', 'take a closer look at'],
  ['deep dive into', 'closer look at'],
  ['unpacking', 'breaking down'],
  ['unpacks', 'breaks down'],
  ['unpacked', 'broke down'],
  ['unpack', 'break down'],
  ['rapidly', 'quickly'],
  ['groundbreaking', 'major'],
  ['invaluable', 'really useful'],
  ['meticulously', 'carefully'],
  ['meticulous', 'careful'],
  ['diligent', 'hardworking'],
  ['cornerstone of', 'key part of'],
  ['linchpin', 'key'],
  ['catalyzing', 'sparking'],
  ['catalyzes', 'sparks'],
  ['catalyzed', 'sparked'],
  ['catalyze', 'spark'],
  ['galvanizing', 'motivating'],
  ['galvanizes', 'motivates'],
  ['galvanized', 'motivated'],
  ['galvanize', 'motivate'],
  ['amplifying', 'boosting'],
  ['amplifies', 'boosts'],
  ['amplified', 'boosted'],
  ['amplify', 'boost'],
  ['augmenting', 'expanding'],
  ['augments', 'expands'],
  ['augmented', 'expanded'],
  ['augment', 'expand'],
  ['bolstering', 'strengthening'],
  ['bolsters', 'strengthens'],
  ['bolstered', 'strengthened'],
  ['bolster', 'strengthen'],
  ['eschew', 'avoid'],
  ['eschews', 'avoids'],
  ['eschewed', 'avoided'],
  ['obviate', 'remove'],
  ['ameliorate', 'improve'],
  ['ameliorates', 'improves'],
  ['exacerbating', 'worsening'],
  ['exacerbates', 'worsens'],
  ['exacerbated', 'worsened'],
  ['exacerbate', 'worsen'],
  ['precipitating', 'triggering'],
  ['precipitates', 'triggers'],
  ['precipitated', 'triggered'],
  ['precipitate', 'trigger'],
  ['corroborating', 'confirming'],
  ['corroborates', 'confirms'],
  ['corroborated', 'confirmed'],
  ['corroborate', 'confirm'],
  ['substantiating', 'backing up'],
  ['substantiates', 'backs up'],
  ['substantiated', 'backed up'],
  ['substantiate', 'back up'],
  ['elucidating', 'explaining'],
  ['elucidates', 'explains'],
  ['elucidated', 'explained'],
  ['elucidate', 'explain'],
  ['explicate', 'explain'],
  ['explicates', 'explains'],
  ['delineating', 'outlining'],
  ['delineates', 'outlines'],
  ['delineated', 'outlined'],
  ['delineate', 'outline'],
  ['enumerating', 'listing'],
  ['enumerates', 'lists'],
  ['enumerated', 'listed'],
  ['enumerate', 'list'],
  ['positing', 'suggesting'],
  ['posits', 'suggests'],
  ['posited', 'suggested'],
  ['posit', 'suggest'],
  ['contending', 'arguing'],
  ['contends', 'argues'],
  ['contended', 'argued'],
  ['contend', 'argue'],
  ['quintessential', 'classic'],
  ['dichotomy', 'divide'],
  ['multifaceted', 'complex'],
  ['interplay between', 'mix of'],
  ['confluence', 'mix'],
  ['amalgamation', 'mix'],
  ['amalgam', 'mix'],
  ['synthesis', 'mix'],
  ['panacea', 'fix'],
  ['watershed moment', 'turning point'],
  ['inflection point', 'turning point'],
  ['step change', 'big change'],
  ['orders of magnitude', 'lot'],
  ['order of magnitude', 'lot'],
  ['exponentially', 'fast'],
  ['proliferating', 'spreading'],
  ['proliferates', 'spreads'],
  ['proliferated', 'spread'],
  ['proliferate', 'spread'],
  ['permeating', 'spreading through'],
  ['permeates', 'spreads through'],
  ['permeated', 'spread through'],
  ['permeate', 'spread through'],
  ['pervading', 'filling'],
  ['pervades', 'fills'],
  ['pervaded', 'filled'],
  ['pervade', 'fill'],
  ['imbued with', 'full of'],
  ['replete with', 'full of'],
  ['fraught with', 'full of'],
  ['beset by', 'hit by'],
  ['beleaguered', 'struggling'],
  ['intrepid', 'brave'],
  ['stalwart', 'loyal'],
  ['venerable', 'respected'],
  ['esteemed', 'respected'],
  ['preeminent', 'top'],
  ['foremost', 'leading'],
  ['renowned', 'famous'],
  ['famed', 'famous'],
  ['insatiable', 'endless'],
  ['unrelenting', 'nonstop'],
  ['inexorable', 'unstoppable'],
  ['tireless', 'dedicated'],
  ['staunch', 'strong'],
  ['ardent', 'passionate'],
  ['fervent', 'passionate'],
  ['zealous', 'eager'],
  ['indomitable', 'unbeatable'],
  ['unassailable', 'solid'],
  ['impeccably', 'perfectly'],
  ['impeccable', 'perfect'],
  ['effortless', 'easy'],
  ['frictionless', 'smooth'],
  ['turnkey', 'ready-made'],
  ['best-of-breed', 'top'],
  ['best of breed', 'top'],
  ['world-class', 'top'],
  ['next-generation', 'new'],
  ['next generation', 'new'],
  ['bleeding-edge', 'new'],
  ['leading-edge', 'latest'],
  ['trailblazing', 'new'],
  ['innovative', 'creative'],
  ['novel', 'fresh'],
  ['transformative', 'powerful'],
  ['game-changing', 'major'],
  ['game changing', 'major'],
  ['revolutionary', 'radical'],
  ['ever-changing', 'changing'],
  ['ever-growing', 'growing'],
  ['ever-increasing', 'rising'],
  ['ever-present', 'constant'],
  ['in a fast-paced world', 'today'],
  ['fast-paced world', 'world'],

  // ---- Stiff verbs -> everyday verbs, wave 2 ----
  ['beginning', 'starting'],
  ['begins', 'starts'],
  ['began', 'started'],
  ['begin', 'start'],
  ['concluding', 'finishing'],
  ['concludes', 'finishes'],
  ['concluded', 'finished'],
  ['conclude', 'finish'],
  ['terminating', 'ending'],
  ['terminates', 'ends'],
  ['terminated', 'ended'],
  ['terminate', 'end'],
  ['enjoying', 'liking'],
  ['enjoys', 'likes'],
  ['enjoyed', 'liked'],
  ['enjoy', 'like'],
  ['resolving', 'fixing'],
  ['resolves', 'fixes'],
  ['resolved', 'fixed'],
  ['resolve', 'fix'],
  ['solving', 'fixing'],
  ['solves', 'fixes'],
  ['solved', 'fixed'],
  ['solve', 'fix'],
  ['verifies', 'checks'],
  ['verified', 'checked'],
  ['verify', 'check'],
  ['selecting', 'picking'],
  ['selects', 'picks'],
  ['selected', 'picked'],
  ['select', 'pick'],
  ['eliminating', 'removing'],
  ['eliminates', 'removes'],
  ['eliminated', 'removed'],
  ['eliminate', 'remove'],
  ['eradicating', 'wiping out'],
  ['eradicates', 'wipes out'],
  ['eradicated', 'wiped out'],
  ['eradicate', 'wipe out'],
  ['reducing', 'cutting'],
  ['reduces', 'cuts'],
  ['reduced', 'cut'],
  ['reduce', 'cut'],
  ['maintaining', 'keeping'],
  ['maintains', 'keeps'],
  ['maintained', 'kept'],
  ['maintain', 'keep'],
  ['examining', 'looking at'],
  ['examines', 'looks at'],
  ['examined', 'looked at'],
  ['examine', 'look at'],
  ['discussing', 'talking about'],
  ['discusses', 'talks about'],
  ['discussed', 'talked about'],
  ['discuss', 'talk about'],
  ['states that', 'says that'],
  ['stated that', 'said that'],
  ['state that', 'say that'],
  ['resembling', 'looking like'],
  ['resembles', 'looks like'],
  ['resembled', 'looked like'],
  ['resemble', 'look like'],
  ['appears to', 'seems to'],
  ['appear to', 'seem to'],
  ['appeared to', 'seemed to'],

  // ---- Stiff adjectives -> plain adjectives ----
  ['minor', 'small'],
  ['antiquated', 'old'],
  ['archaic', 'old'],
  ['additional', 'more'],
  ['complimentary shipping', 'free shipping'],
  ['complimentary trial', 'free trial'],
  ['complimentary access', 'free access'],
  ['fraudulent', 'fake'],
  ['genuine', 'real'],
  ['authentic', 'real'],
  ['entire', 'whole'],
  ['optimal', 'best'],
  ['ideal', 'perfect'],
  ['delighted', 'happy'],
  ['thrilled', 'excited'],
  ['displeased', 'unhappy'],
  ['dissatisfied', 'unhappy'],
  ['exhausted', 'tired'],
  ['fatigued', 'tired'],
  ['intelligent', 'smart'],
  ['make certain', 'make sure'],
  ['be certain', 'be sure'],

  // ---- Stiff adverbs/time -> plain ----
  ['frequently', 'often'],
  ['occasionally', 'sometimes'],
  ['invariably', 'always'],
  ['approximately', 'about'],
  ['currently', 'now'],
  ['presently', 'now'],
  ['at present', 'now'],
  ['quickly', 'fast'],
  ['merely', 'just'],

  // ---- More contractions AI text leaves expanded ----
  ['what is', "what's"],
  ['who is', "who's"],
  ['here is', "here's"],

  // ---- Strong-only casualization ----
  ['a lot of', 'tons of', 2],
  [/(?<!would\s)\brather\b/gi, 'pretty', 2],
  [/\bquite\b(?!\s+a\s+few)(?!\s+the\b)/gi, 'pretty', 2],

  // ---- Stiff nouns -> plain nouns ----
  ['aspects', 'parts'],
  ['aspect', 'part'],
  ['elements', 'parts'],
  ['element', 'part'],
  ['components', 'parts'],
  ['component', 'part'],

  // ---- Second person: AI writes impersonally, humans address the reader ----
  ['one can', 'you can'],
  ['one should', 'you should'],
  ['one must', 'you have to'],
  ['it is possible to', 'you can'],
  ['it is easy to', 'you can easily'],

  // ---- Strong-only: bold voice changes (grammatically safe imperatives) ----
  ['it is important to', 'be sure to', 2],
  ['it is essential to', 'be sure to', 2],
  ['it is crucial to', 'make sure to', 2],

  // ---- Raw patterns (capture groups; used as-is) ----
  [/(\d+)\s+percent\b/gi, '$1%'],
  [/(\$?)(\d[\d,]*)\s+dollars\b/gi, (m, dol, num) => (dol || '$') + num],

  // ---- Contractions humans use, AI often avoids (always safe) ----
  ['cannot', "can't"],
  ['do not', "don't"],
  ['does not', "doesn't"],
  ['did not', "didn't"],
  ['will not', "won't"],
  ['would not', "wouldn't"],
  ['should not', "shouldn't"],
  ['could not', "couldn't"],
  ['is not', "isn't"],
  ['are not', "aren't"],
  ['was not', "wasn't"],
  ['were not', "weren't"],
  ['have not', "haven't"],
  ['has not', "hasn't"],
  ['had not', "hadn't"],
  ['it is', "it's"],
  ['that is', "that's"],
  ['there is', "there's"],
  ['you will', "you'll"],
  ['we will', "we'll"],
  ['they will', "they'll"],
  ['it will', "it'll"],
  ['that will', "that'll"],
  ['i will', "I'll"],
  ['you have', "you've"],
  ['we have', "we've"],
  ['they have', "they've"],
  ['i have', "I've"],
  ['you are', "you're"],
  ['we are', "we're"],
  ['they are', "they're"],
  ['you would', "you'd"],
  ['we would', "we'd"],
  ['they would', "they'd"],
  ['i would', "I'd"],
];

// Sentence openers that scream "AI" when repeated. Normalized to a natural
// base form first; consecutive duplicates are then rotated to a synonym so
// no two sentences in a row start the same way (a strong detector signal).
const OPENER_BASE = [
  ['moreover,', 'also,'],
  ['furthermore,', 'also,'],
  ['additionally,', 'also,'],
  ['in addition,', 'also,'],
  ['however,', 'but,'],
  ['therefore,', 'so,'],
  ['thus,', 'so,'],
  ['hence,', 'so,'],
  ['nevertheless,', 'still,'],
  ['nonetheless,', 'still,'],
  ['in conclusion,', 'so,'],
  ['lastly,', 'finally,'],
];
const OPENER_ROTATION = {
  // '' = drop the opener entirely ("Also, note that..." -> "Note that..."),
  // the way a human editor varies rhythm — by omission, not decoration.
  'also,': ['also,', 'and', ''],
  'but,': ['but,', 'still,', ''],
  'so,': ['so,', 'then,', ''],
  'still,': ['still,', 'but,', ''],
  'and,': ['and,', 'also,', ''],
};

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Abbreviations that contain periods must survive the whole pipeline
// (splitting + capitalization), so they are masked at the start and
// restored at the very end.
const EG_TOKEN = 'E\x1bG';
const IE_TOKEN = 'I\x1bE';

export class TextHumanizer {
  preserveCase(match, replacement) {
    if (!match || !replacement) return replacement;
    if (match === match.toUpperCase()) return replacement.toUpperCase();
    if (match[0] === match[0].toUpperCase()) {
      return replacement[0].toUpperCase() + replacement.slice(1);
    }
    return replacement;
  }

  applyReplacements(text, level = 0) {
    // Longest patterns first so "a large number of" wins over shorter ones.
    const keyLen = (e) => (e[0] instanceof RegExp ? e[0].source.length : e[0].length);
    const entries = [...REPLACEMENTS].sort((a, b) => keyLen(b) - keyLen(a));
    for (const [src, rep, minLevel = 0] of entries) {
      if (level < minLevel) continue;
      if (src instanceof RegExp) {
        // Raw pattern: fresh instance each call (avoids lastIndex state bugs).
        text = text.replace(new RegExp(src.source, src.flags), rep);
      } else {
        const re = new RegExp('\\b' + escapeRegExp(src) + '\\b', 'gi');
        text = text.replace(re, (m) => this.preserveCase(m, rep));
      }
    }
    return text;
  }

  splitSentences(text) {
    // Tokens contain no periods, so abbreviations never cause a split.
    const parts = text
      .split(/(?<=[.!?])\s+(?=[A-Z0-9"'“(\[])/)
      .map((s) => s.trim())
      .filter((s) => s.length > 0);
    return parts.length > 0 ? parts : [text.trim()];
  }

  // Break sentences longer than maxWords at a natural joint. Splitting long,
  // uniform AI sentences into mixed short/long ones creates "burstiness" —
  // the main thing detectors measure. Every split yields COMPLETE sentences
  // (conjunctions are absorbed, never stranded into fragments).
  splitLongSentences(sentences, maxWords, mode) {
    // A which-split inserts "This" so the new sentence stands alone
    // ("..., which tracks X." -> "This tracks X."). Bare 'that' is never
    // split: it is often a complementizer ("said that..."), where a split
    // would break grammar.
    const verbGuard = /^(is|was|are|were|will|would|can|could|has|have|had|means|meant|makes|made|shows|showed|tracks|track)\b/i;
    const lightJoints = [
      { re: /; / }, { re: /, and /i }, { re: /, but /i }, { re: /, or /i },
      { re: /, so /i }, { re: / which /i, guard: true, insert: 'This' },
      { re: / because /i }, { re: / while /i }, { re: / whereas /i },
    ];
    const boldJoints = [
      { re: / because /i }, { re: / while /i }, { re: / whereas /i },
      { re: / when /i }, { re: / if /i }, { re: / though /i }, { re: / although /i },
      { re: / which /i, guard: true, insert: 'This' }, { re: /; / },
      { re: /, and /i }, { re: /, but /i }, { re: /, or /i }, { re: /, so /i },
    ];
    const joints = mode === 'light' ? lightJoints : boldJoints;
    const out = [];
    for (const s of sentences) {
      const words = s.split(/\s+/);
      if (words.length <= maxWords) {
        out.push(s);
        continue;
      }
      let splitAt = -1;
      let jointLen = 0;
      let jointInsert = null;
      for (const j of joints) {
        const rx = new RegExp(j.re.source, 'gi');
        let m;
        while ((m = rx.exec(s)) !== null) {
          // Off-center splits are fine (short + long = burstiness); avoid stubs.
          if (m.index < s.length * 0.15 || m.index > s.length * 0.85) continue;
          const after = s.slice(m.index + m[0].length).trim();
          // For which-splits, the clause needs a leading verb to stand alone.
          if (j.guard && !verbGuard.test(after)) continue;
          splitAt = m.index;
          jointLen = m[0].length;
          jointInsert = j.insert || null;
          break;
        }
        if (splitAt !== -1) break;
      }
      if (splitAt === -1) {
        out.push(s);
        continue;
      }
      const first = s.slice(0, splitAt).replace(/[,;]$/, '').trim() + '.';
      let second = s.slice(splitAt + jointLen).trim();
      if (jointInsert) {
        second = jointInsert + ' ' + second.charAt(0).toLowerCase() + second.slice(1);
      } else {
        second = second.charAt(0).toUpperCase() + second.slice(1);
      }
      out.push(first, second);
    }
    return out;
  }

  normalizeOpeners(sentences) {
    // 1) map AI openers to their natural base form (case-preserving)
    let mapped = sentences.map((s) => {
      for (const [src, rep] of OPENER_BASE) {
        const re = new RegExp('^' + escapeRegExp(src) + '\\s+', 'i');
        const m = s.match(re);
        if (m) return this.preserveCase(m[0].trim(), rep) + ' ' + s.slice(m[0].length);
      }
      return s;
    });
    // 2) rotate consecutive duplicates: "Also, ... Also, ..." never survives.
    // A repeated opener becomes a synonym, then is dropped outright.
    const seen = {};
    mapped = mapped.map((s) => {
      const m = s.match(/^([A-Za-z]+,?)\s+/);
      if (!m || !m[1].endsWith(',')) return s;
      const key = m[1].toLowerCase();
      const variants = OPENER_ROTATION[key];
      if (!variants) return s;
      seen[key] = (seen[key] || 0) + 1;
      const pick = variants[(seen[key] - 1) % variants.length];
      if (pick.toLowerCase() === key) return s;
      const rest = s.slice(m[0].length);
      if (pick === '') {
        // Drop the opener; re-capitalize the new sentence start.
        return rest.charAt(0).toUpperCase() + rest.slice(1);
      }
      const cap = m[1][0] === m[1][0].toUpperCase();
      const word = cap ? pick[0].toUpperCase() + pick.slice(1) : pick;
      return word + ' ' + rest;
    });
    return mapped;
  }

  normalizePunctuation(text) {
    let t = text;
    t = t.replace(/ — /g, ', ');
    t = t.replace(/ – /g, ', ');
    // Semicolons joining clauses -> full stop (humans use short sentences).
    t = t.replace(/;\s*/g, '. ');
    t = t.replace(/\s+([.,!?;:])/g, '$1'); // no space before punctuation
    t = t.replace(/([.,!?;:])([A-Za-z])/g, '$1 $2'); // space after punctuation
    t = t.replace(/\s+/g, ' ').trim();
    // Capitalize the first letter of every sentence.
    t = t.replace(/(^|[.!?]\s+)([a-z])/g, (m, p1, p2) => p1 + p2.toUpperCase());
    // Standalone "i" -> "I".
    t = t.replace(/\bi\b/g, 'I');
    return t;
  }

  // Strong-only, max once: turn one short plain middle declarative into a
  // rhetorical question ("Teams should use these tools." ->
  // "Why wouldn't teams use these tools?"). Questions are high-perplexity
  // for detectors and natural for humans. Tight guards keep it grammatical.
  toQuestion(sentences) {
    for (let i = 1; i < sentences.length - 1; i++) {
      const s = sentences[i];
      if (/^[A-Za-z]+,/.test(s)) continue;
      if (/[?!:;,]/.test(s)) continue;
      const m = s.match(/^([A-Z][A-Za-z ]+?) should ([a-z].+)\.$/);
      if (!m) continue;
      const subj = m[1].trim();
      const rest = m[2].trim();
      if (subj.split(/\s+/).length > 4) continue;
      if (rest.split(/\s+/).length > 8) continue;
      if (/^(I|We|You|He|She|It|They)\b/i.test(subj)) continue;
      sentences[i] = `Why wouldn't ${subj.charAt(0).toLowerCase() + subj.slice(1)} ${rest}?`;
      return true;
    }
    return false;
  }

  // Strong-only, max once: give one short punchy sentence an exclamation
  // ("The results were impressive!"). Punctuation variety breaks the flat
  // declarative rhythm detectors expect.
  toExclaim(sentences) {
    const strongAdj = /impressive|amazing|great|excellent|huge|massive|incredible|fantastic|powerful|awesome|remarkable/i;
    for (let i = 0; i < sentences.length; i++) {
      const s = sentences[i];
      if (!/\.$/.test(s)) continue;
      if (/[?!:;,]/.test(s)) continue;
      if (s.split(/\s+/).length > 9) continue;
      if (!strongAdj.test(s)) continue;
      sentences[i] = s.replace(/\.$/, '!');
      return true;
    }
    return false;
  }

  humanize(text, intensity = 'medium') {
    if (!text || !text.trim()) return text;
    const level = intensity === 'light' ? 0 : intensity === 'strong' ? 2 : 1;

    let result = text
      .replace(/e\.g\./gi, EG_TOKEN)
      .replace(/i\.e\./gi, IE_TOKEN);
    result = this.applyReplacements(result, level);
    let sentences = this.splitSentences(result);

    const maxWords = intensity === 'light' ? 1000 : intensity === 'strong' ? 18 : 24;
    if (maxWords < 1000) {
      sentences = this.splitLongSentences(sentences, maxWords, intensity);
    }

    sentences = this.normalizeOpeners(sentences);

    if (intensity === 'strong') {
      this.toQuestion(sentences);
      this.toExclaim(sentences);
    }

    result = this.normalizePunctuation(sentences.join(' '));
    result = result.split(EG_TOKEN).join('e.g.').split(IE_TOKEN).join('i.e.');
    return result;
  }
}

export const humanizer = new TextHumanizer();

export default humanizer;
